### ISSUE TITLE
Error installing rdf-tabular

### ISSUE THREAD

**Issue by jcoyne** [ruby-rdf/rdf-tabular#2]
```
Gem::Package::PathError: installing into parent path

/home/travis/.rvm/gems/ruby-2.3.0/gems/w3c-csvw of

/home/travis/.rvm/gems/ruby-2.3.0/gems/rdf-tabular-1.0.0 is not allowed

An error occurred while installing rdf-tabular (1.0.0), and Bundler

cannot continue.

Make sure that `gem install rdf-tabular -v '1.0.0'` succeeds before

bundling.
```

**Comment by jcoyne** [comment]
I see this on travis, but I can't reproduce it locally. https://travis-ci.org/projecthydra-labs/questioning_authority/builds/188865444

**Comment by gkellogg** [comment]
Thanks, I think there is a symlink in the spec dir to w3c-csvw that might not be ignored; I'll check it out.

**Comment by gkellogg** [comment]
There is provision for a `w3c-csvw` symlink in spec, but it's specifically added to .gitignore. There's code in `spec/suite_helper.rb` that checks to see if a test-suite file exists using the path before retrieving it over the net. On travis, this is avoided by setting the `CI=true` environment variable.

Prior to October 9th (commit c8890fed79fa597255f0da100c604a1ee942af19, the symlink wasn't in .gitignore, so you may have imported it accidentally along the way, now it remains, but is in .gitignore.

I'm out for a bit, so can't spend any detailed time on this right now.

**Comment by gkellogg** [comment]
@jcoyne It looks like this happened on https://github.com/projecthydra-labs/questioning_authority branch v0.11.0, which no longer exists. Are you still experiencing the problem?

**Comment by gkellogg** [comment]
Reopen if this continues to be an issue; doesn't seem like anything active with the gem at this point.

**Comment by jcoyne** [comment]
Yes, perhaps it was cached on Travis.  Not really an issue at the moment.

**Comment by jcoyne** [comment]
Seeing this again in https://travis-ci.org/projecthydra/ldp/jobs/191714607#L461

**Comment by jcoyne** [comment]
Clearing the caches and restarting the build did not fix it. Perhaps this is only an issue on ruby 2.3.0?

**Comment by gkellogg** [comment]
I can't see how it would be a ruby 2.3.0 issue. I again can't reproduce this, so I can't see how it could be anything other than a caching problem.

There is a case when we try to access spec/w3c-csvw when running specs in rdf-tabular, but you're not doing that. In any case, this would refer to an old symlink from spec/w3c-csvw to ../../w3c-csvw which is what it seems to be complaining about.

The only other thing I can try is to yank the gem which included the symlink.

Also, you could try using the git-repo for rdf-tabular in your Gemfile, but that certainly shouldn't be necessary.

**Comment by gkellogg** [comment]
Okay, it was only in 0.0.1, which I yanked from rubygems.

**Comment by gkellogg** [comment]
Found the problem, it was in the .gemspec where it was adding all the contents from the spec directory, including the symlink. I'll release version 2.2.0 to fix this, and bring it in line with RDF.rb versioning.

**Comment by gkellogg** [comment]
@jcoyne if you need a patch on an earlier version of RDF.rb, let me know.

**Comment by jcoyne** [comment]
@gkellogg Excellent find. Thanks for tracking this down.

**Comment by gkellogg** [comment]
I'll need to update linked-data, as it has a dependency on rdf-tabular that doesn't pull in 2.2.0

**Comment by gkellogg** [comment]
Okay, should be good now.
