### ISSUE TITLE
Cannot use external metadata

### ISSUE THREAD

**Issue by workergnome** [ruby-rdf/rdf-tabular#3]
Given a directory that includes both a `data.csv` and an `alternate-data.csv`, and given code that looks something like this:

```ruby
require 'linkeddata'

RDF::Tabular::Reader.open("alternate-data.csv", metadata: "data.csv-metadata.json") do |reader|
  puts reader.inspect
  
  reader.each do |statement|
    puts statement.inspect
  end
end
```

and a `data.csv-metadata.json` that looks something like this:

```
{
  "@context": "http://www.w3.org/ns/csvw",
  "url": "data.csv",
  "tableSchema": {
    "primaryKey": "id",
    "columns": [
      {
        "titles": "id",
        "name": "id",
        "datatype": "string",
        "required": true
      }]
}
```

The code executes, but it processes `data.csv`, not `alternate-data.csv`.

If, in `lib/rdf/tabular/reader.rb` I comment out the [the last half of line 135](https://github.com/ruby-rdf/rdf-tabular/blob/develop/lib/rdf/tabular/reader.rb#L135), so

```ruby
 @options[:original_input] = @input #unless @options[:metadata]
```

instead of 

```ruby
 @options[:original_input] = @input unless @options[:metadata]
```

it functions correctly.

It looks like there's an edge case where that and [line 183](https://github.com/ruby-rdf/rdf-tabular/blob/develop/lib/rdf/tabular/reader.rb#L183) don't work together in this case.  The tests pass either way, but it seems unlikely that it was just left in accidentally.

**Comment by gkellogg** [comment]
It should detect an error, as the metadata must reference the CSV it is used with. In this case, you referenced both the metadata and input, but they disagree.

I know it would be useful to be able to re-use metadata with different CSV files, but this is specifically disallowed by the spec (it was an original design goal, but proved to be problematic).

The last half of line 35 is when metadata is either specified, or has been detected and we restart using that metadata, so it is intentional.

**Comment by workergnome** [comment]
Thank you for clarifying.  I'll work around it on my end, then—still figuring out how all this works.

**Comment by gkellogg** [comment]
The requirements of locating metadata, and in turn, having the metadata identify the CSV do may this more challenging than other RDF formats, unfortunately.

**Comment by bencomp** [comment]
> I know it would be useful to be able to re-use metadata with different CSV files, but this is specifically disallowed by the spec (it was an original design goal, but proved to be problematic).

There is a way to reuse the table schema definitions, namely by putting the *schema* in a separate file and referencing it for each of the tables. Your metadata would like these two files:

```
{
  "@context": "http://www.w3.org/ns/csvw",
  "tables": [
   {  
    "url": "data.csv",
    "tableSchema": { "@id": "schema.json" }
   },
   {  
    "url": "alternate-data.csv",
    "tableSchema": { "@id": "schema.json" }
   }
  ]
}
```

```
{
  "@id": "schema.json",
  "primaryKey": "id",
  "columns": [
      {
        "titles": "id",
        "name": "id",
        "datatype": "string",
        "required": true
      }
  ]
}
```

**Comment by workergnome** [comment]
Thanks!  That's a good workaround.
