### ISSUE TITLE
Use it in shell

### ISSUE THREAD

**Issue by ktk** [ruby-rdf/rdf-tabular#4]
I have zero Ruby knowledge so I tried to figure out how to use rdf-tabular. My expectations were that there is an executable/binary somewhere where I can provide some command line arguments like CSV input file, configuration, output format etc. Basically everything I would need if I would want to automate transformation in a shell.

Am I right that this is currently not possible? Examples only show Ruby code and all I want to do is write a bunch of shell scripts.

**Comment by gkellogg** [comment]
There is an `rdf` executable which is installed when you install rdf-tabular. If you do a `gem install rdf-tabular`, it will install the `rdf` executable in the standard Ruby bin dir, which varies depending on the system you're running. In my case, it is installed into /usr/local/bin/rdf.

The `rdf` exe is a Ruby script, itself, which runs Ruby code from the gems You can try, for example,

```
rdf serialize https://raw.githubusercontent.com/ruby-rdf/rdf-tabular/develop/etc/doap.csv --output-format ttl
```

You can validate using:

```
rdf validate https://raw.githubusercontent.com/ruby-rdf/rdf-tabular/develop/etc/doap.csv
```

To get the rdf-tabular specific functions, you need to use the `--input-format tabular` option, then you can get the Tabular JSON output:

```
rdf tabular-json --input-format tabular https://raw.githubusercontent.com/ruby-rdf/rdf-tabular/develop/etc/doap.csv
```

The `--help` option will tell you other options and commands you can run. You might want the `--minimal` option to remove the provenance information from the output, for example.

It would be reasonable to have a section on this in the README (and for other gems as well), so we'll leave this open until that has been resolved.

**Comment by ktk** [comment]
@gkellogg thanks a lot for the explanation. I saw the `rdf` binary but the options didn't hint that I can use this for transformation. Will work with that, thanks!

Something else: Do I have to write the mapping in JSON-LD? I really dislike JSON-LD and am much faster in writing Turtle but in the spec everything seems to be JSON-LD.

**Comment by gkellogg** [comment]
If by "mapping", you mean the CSVW Metadata file, then he's, this is a proscribed format based on JSON-LD. Note that RDF is an output option, and the spec itself just uses JSON and CSV.
