### ISSUE TITLE
Data Cube example fails

### ISSUE THREAD

**Issue by ktk** [ruby-rdf/rdf-tabular#6]
I've tried the [Data Cube example](https://github.com/w3c/csvw/blob/gh-pages/examples/rdf-data-cube-example.md) linked in the Github directory of CSVW:

    rdf serialize https://raw.githubusercontent.com/w3c/csvw/gh-pages/examples/cambornedata.csv --output-format ttl

And I get:

```
/usr/local/bundle/gems/rdf-tabular-2.2.0/lib/rdf/tabular/metadata.rb:1864:in `block (2 levels) in embedded_metadata': undefined method `lstrip!' for nil:NilClass (NoMethodError)
[...]
```

Any ideas what is missing here?

**Comment by bencomp** [comment]
I see the same error message. The line throwing the error is https://github.com/ruby-rdf/rdf-tabular/blob/897c29ed0fd1f8a12d337900fa07937c349e8568/lib/rdf/tabular/metadata.rb#L1864

rdf-tabular is trying to extract metadata from the CSV file itself ("embedded metadata"). It looks like the 'offending' line is trying to trim the empty cells in the header:
```
yyyy,mm,tmax, ,tmin, ,af, ,rain, ,sun, , 
,,degC,,degC,,days,,mm,,hours,,
```

After reading the [cambornedata.csv-metadata.json](https://raw.githubusercontent.com/w3c/csvw/gh-pages/examples/cambornedata.csv-metadata.json) and the [Tabular metadata section on Inherited properties](https://www.w3.org/TR/2015/REC-tabular-metadata-20151217/#inherited-properties), it looks like only `---` should count as `null` in these cells. rdf-tabular may incorrectly(?) treat the empty cells as `nil` too, which would explain that they cannot be trimmed. (`trim` is not specified in the dialect description in the metadata, so it defaults to `true`.)

I could be wrong about this, however, as I don't fully understand Ruby or rdf-tabular. :)

**Comment by gkellogg** [comment]
I fixed the strip issue, but note that not all examples in the examples directory are valid, but were used as use cases. In fact, the cambornedata does not seem to be valid; the titles are inconstant with the metadata, and it has extra blank columns.
