### ISSUE TITLE
Serialise command requires `--input-format`?

### ISSUE THREAD

**Issue by Robsteranium** [ruby-rdf/rdf-tabular#8]
The readme states that:

> To use RDF::Tabular specific features, you must use the --input-format tabular option to the rdf executable. Other rdf commands and options treat CSV as a standard RDF format.

and provides an example:
```
rdf serialize https://raw.githubusercontent.com/ruby-rdf/rdf-tabular/develop/etc/doap.csv  --output-format ttl
```

This fails for me with:
```
ERROR [line 1] Lexer error: With input ...
FATAL recovery:   statement: ["."]
```

It seems to work fine if I do specify the --input-format option:
```
rdf serialize --input-format tabular https://raw.githubusercontent.com/ruby-rdf/rdf-tabular/develop/etc/doap.csv  --output-format ttl
```

rdf 3.0.1, rdf-tabular 2.2.1

**Comment by gkellogg** [comment]
Fixed in RDF.rb 3.0.2. Github returns content-type text/plain, which is fooling `RDF::Reader.open` to not use the file name. Updated `RDF::Reader.open` to ignore content-type if it includes text/plain.
